### ISSUE TITLE
panic: user: unknown userid

### ISSUE THREAD

**Issue by neechbear** [acarl005/ls-go#12]
Panics when encountering a file or directory where there is no user mapping. Presumably the same will happen for non-mapped groups.

```
uname -a
Linux laptop 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
```

```
go version
go version go1.9 linux/amd64
```

```
v0.0.2 
nicolaw@laptop: ~/go/src/github.com/acarl005/ls-go $ git rev-parse HEAD 
187bc787f33b3c1a82f68d3b3de205f3a26e79b9
```

```
panic: user: unknown userid 999

goroutine 1 [running]:
main.check(0x74c0e0, 0xc420390508)
	/home/nicolaw/go/src/github.com/acarl005/ls-go/ls-go.go:603 +0x4a
main.getOwnerAndGroup(0xc42004f9d8, 0xc420019304, 0x7, 0xc4203904f0, 0x7)
	/home/nicolaw/go/src/github.com/acarl005/ls-go/ls-unix.go:22 +0x18e
main.listFiles(0xc42038e640, 0x15, 0xc42004fbe8, 0x0)
	/home/nicolaw/go/src/github.com/acarl005/ls-go/ls-go.go:147 +0x1a8
main.listDir(0xc42038e640, 0x15)
	/home/nicolaw/go/src/github.com/acarl005/ls-go/ls-go.go:121 +0x31e
main.listDir(0xc4204c45c0, 0xb)
	/home/nicolaw/go/src/github.com/acarl005/ls-go/ls-go.go:128 +0x2d9
main.listDir(0x631b44, 0x1)
	/home/nicolaw/go/src/github.com/acarl005/ls-go/ls-go.go:128 +0x2d9
main.main()
	/home/nicolaw/go/src/github.com/acarl005/ls-go/ls-go.go:86 +0x4ac
```

**Comment by acarl005** [comment]
Try again? Should be fixed

**Comment by acarl005** [comment]
Will reopen if this is still an issue.
