### ISSUE TITLE
ls with wrong argument panics

### ISSUE THREAD

**Issue by Wouterbeets** [acarl005/ls-go#5]
if i'm in a directory with a file named bar
if I run ` ls-go baz` I get a panic.
```
panic: stat baz: no such file or directory

goroutine 1 [running]:
main.check(0x74eb40, 0xc4200112c0)
	/home/bugless/src/github.com/acarl005/ls-go/ls-go.go:478 +0x4a
main.main()
	/home/bugless/src/github.com/acarl005/ls-go/ls-go.go:59 +0x1dd

```

**Comment by acarl005** [comment]
This should be fixed. Will reopen if its still an issue.
