### ISSUE TITLE
ls-go painic when file group is unkonwn

### ISSUE THREAD

**Issue by jsfaint** [acarl005/ls-go#8]
When the group is unknown, ls-go will show the error below, then panic
```go
panic: group: unknown groupid 1000

goroutine 1 [running]:
main.check(0x63fa20, 0xc42007e830)
        /home/jiasui/repos/ls-go/src/github.com/acarl005/ls-go/ls-go.go:603 +0x4a
main.getOwnerAndGroup(0xc4200ddc30, 0x1a4, 0x0, 0x0, 0x1)
        /home/jiasui/repos/ls-go/src/github.com/acarl005/ls-go/ls-unix.go:24 +0x1b4
main.listFiles(0x619564, 0x1, 0xc4200dde38, 0x0)
        /home/jiasui/repos/ls-go/src/github.com/acarl005/ls-go/ls-go.go:189 +0x59f
main.listDir(0x619564, 0x1)
        /home/jiasui/repos/ls-go/src/github.com/acarl005/ls-go/ls-go.go:121 +0x2e8
main.main()
        /home/jiasui/repos/ls-go/src/github.com/acarl005/ls-go/ls-go.go:86 +0x45d
```

Reproduce step:
1. touch 123
2. chown jiasui:1000 123
3. Run ls-go

**Comment by jsfaint** [comment]
Sorry this issue is duplicate with #4
Close it.
